# Deploy to Firebase Hosting on push to main branch
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Firebase Service Account
        run: |
          if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT_HYOUKA_DB }}" ]; then
            echo "❌ Firebase service account secret not found"
            exit 1
          else
            echo "✅ Firebase service account secret is configured"
          fi

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HYOUKA_DB }}'
          channelId: live
          projectId: hyouka-db
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: Log deployment success
        if: success()
        run: |
          echo "🎉 Firebase Hosting Deployment Successful!"
          echo "📍 Live URL: https://hyouka-db.web.app"
          echo "📍 Alt URL: https://hyouka-db.firebaseapp.com"
          echo "✅ CORS issues resolved!"
          echo "✅ Firebase Authentication working"
          echo "✅ PWA features enabled"

      - name: Log deployment failure
        if: failure()
        run: |
          echo "❌ Firebase Hosting Deployment Failed"
          echo "Please check:"
          echo "1. Firebase service account secret is properly configured"
          echo "2. Project ID is correct: hyouka-db" 
          echo "3. Firebase project has Hosting enabled"
          echo "🔧 Alternative: Run ./deploy.sh from local machine"