# Deploy to Firebase Hosting on push to main branch
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HYOUKA_DB }}'
          channelId: live
          projectId: hyouka-db
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: Comment deployment URL
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: '🚀 **Deployed to Firebase Hosting!**\n\n📍 **Live URL**: https://hyouka-db.web.app\n📍 **Alt URL**: https://hyouka-db.firebaseapp.com\n\n✅ CORS issues resolved!'
            })